import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'zh' | 'en';

const zhTranslations = {
  common: {
    confirm: '确认',
    cancel: '取消',
    all: '全部',
    selectAll: '全选',
    deselectAll: '取消全选',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    view: '查看',
    search: '搜索',
    reset: '重置',
    submit: '提交',
    back: '返回',
    next: '下一步',
    close: '关闭',
    copy: '复制',
    loading: '加载中',
    noData: '暂无数据',
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '提示',
    actions: '操作',
    remark: '备注',
    createdAt: '创建时间',
    updatedAt: '更新时间',
    time: '时间',
    logTime: '日志时间',
    pleaseLogin: '请先登录',
    permissionDenied: '权限不足，无法访问该页面',
    roleDenied: '角色权限不足，无法访问该页面',
    noPermissionTitle: '无访问权限',
    noPermissionHint: '抱歉，您没有访问此页面的权限。请联系管理员获取相应权限。',
  },
  systemManage: {
    importExport: {
      importTitle: '导入数据',
      exportTitle: '导出数据',
      supportFiles: '支持文件',
      exportFormat: '导出格式',
      clickToUpload: '点击上传',
      dragAndDrop: '拖拽文件到此处',
      maxSize: '最大大小',
      downloadTemplate: '下载模板',
      processing: '处理中',
      exportAll: '导出全部',
      exportSelected: '导出所选',
      error: '处理失败',
    },
  },
  system: {
    title: '运维管理平台',
    subtitle: '统一监控与运维中心',
    admin: '管理员',
    adminEmail: '管理员邮箱',
    addMenuTitle: '新增菜单',
    addMenuDescription: '创建新的导航菜单项',
    addRoleTitle: '新增角色',
    addRoleDescription: '创建新的系统角色并分配权限',
    addUserTitle: '新增用户',
    addUserDescription: '创建新的系统用户账号',
  },
  topBar: {
    searchPlaceholder: '搜索...',
    theme: '主题',
    language: '语言',
    languageChinese: '中文',
    languageEnglish: 'English',
    notifications: '通知',
    myAccount: '我的账户',
    profile: '个人资料',
    profileCenter: '个人中心',
    accountSettings: '设置',
    logout: '退出登录',
    noNewNotifications: '暂无新通知',
  },
  notification: {
    inbox: '收件箱',
    templates: '通知模板',
  },
  footer: {
    copyright: '运维管理系统',
    database: '数据库',
    cache: '缓存',
    systemStatus: '系统运行状态',
    normal: '正常',
    error: '异常',
  },
  menu: {
    dashboard: '仪表盘',
    systemOverview: '系统概览',
    hosts: '主机管理',
    k8s: 'K8s 集群',
    k8sClusters: 'K8s 集群列表',
    k8sNodes: 'K8s 节点管理',
    k8sWorkloads: 'K8s 工作负载',
    k8sNetwork: 'K8s 网络服务',
    k8sRouting: 'K8s 应用路由',
    deploy: '部署中心',
    operations: '运维管理',
    alert: '监控告警',
    alertMonitor: '监控中心',
    alertManagement: '告警管理',
    alertRules: '告警规则',
    alertHistory: '告警历史',
    alertNotification: '通知设置',
    system: '系统管理',
    systemUsers: '用户管理',
    systemDepartments: '部门管理',
    systemPositions: '岗位管理',
    systemRoles: '角色管理',
    systemMenus: '菜单管理',
    systemPermissions: '权限管理',
    systemLogs: '系统日志',
    systemAudit: '审计日志',
    systemSettings: '系统设置',
    systemDictionary: '数据字典',
    systemMonitor: '系统监控',
    systemLogManagement: '日志管理',
    profile: '个人中心',
    tenantManagement: '租户管理',
  },
  systemManagement: {
    title: '系统管理',
    description: '管理系统用户、权限和配置',
    permissionMatrix: '权限矩阵',
    permissionAudit: '权限审计',
    loginLogs: '登录日志',
    dashboard: {
      location: '上海, 中国',
      greetings: {
        morning: '早上好',
        afternoon: '下午好',
        evening: '晚上好',
      },
      adminFallback: '管理员',
      welcomeBack: '欢迎回到 Pantheon 管理系统',
      currentDate: '当前日期',
      quickActions: {
        addUser: '新增用户',
        authorizeRole: '角色授权',
        configureMenu: '菜单配置',
        manageDictionary: '字典管理',
        auditLogs: '审计日志',
        databaseBackup: '数据库备份',
      },
    },
    roles: {
      usersDialog: {
        title: '角色成员管理',
        description: '为角色添加或移除成员，维护角色的成员列表。',
        tabCurrent: '当前成员',
        tabAdd: '添加成员',
        searchPlaceholder: '搜索用户姓名、账号或邮箱...',
        selectedLabel: '已选择',
        emptyCurrent: '该角色暂无成员',
        emptySearch: '未找到匹配的用户',
        removeSelected: '移除所选',
        addSelected: '添加所选',
        removeSuccess: '成员已移除',
        addSuccess: '成员已添加',
      },
    },
    users: {
      actions: {
        assignRoles: '分配角色',
        resetPassword: '重置密码',
      },
      permissionsPanel: {
        title: '用户权限',
        description: '查看该用户聚合后的权限列表（来自角色绑定的 Casbin 策略）。',
        total: '总权限数',
        searchPlaceholder: '搜索权限标识...',
        verifyTitle: '权限验证',
        verifyHint: '输入权限标识进行验证（例如：/api/v1/system/users:get）',
        verifyPlaceholder: '输入权限标识',
        verifyButton: '验证',
        verifyHas: '用户拥有此权限',
        verifyNot: '用户不拥有此权限',
      },
      roleAssignDialog: {
        title: '分配角色',
        description: '为用户分配或移除角色',
        selectRoles: '选择该用户的角色',
        systemRole: '系统',
        customRole: '自定义',
        setExpiry: '设置有效期',
        expiryPlaceholder: '选择到期日期',
        updated: '角色已更新',
        updateFailed: '更新角色失败',
        tipAssignPrefix: '将分配',
        tipRoleSuffix: '个角色',
        tipUntil: '有效期至',
        rolesLabel: '选择角色',
        searchPlaceholder: '搜索角色...',
      },
      form: {
        usernamePlaceholder: '请输入用户名',
        realNamePlaceholder: '请输入姓名',
        emailPlaceholder: '请输入邮箱',
        phonePlaceholder: '请输入手机号',
        passwordPlaceholder: '请输入密码',
        departmentPlaceholder: '请选择部门',
        rolePlaceholder: '请选择角色',
        remarkPlaceholder: '请输入备注信息',
      },
    },
    positions: {
      level: '职级',
      levelAll: '所有职级',
      levelL1: 'L1 职级',
      levelL2: 'L2 职级',
      levelL3: 'L3 职级',
    },
    dictionary: {
      typeTitle: '字典分类',
      typeSearchPlaceholder: '搜索分类...',
      typeEmptyHint: '暂无匹配分类',
      searchPlaceholder: '搜索字典项...',
      addItem: '新增项目',
      typeKey: '分类 Key',
      unselected: '未选择',
      refresh: '刷新',
      addCategoryTodo: '新增分类功能开发中',
      selectTypeFirst: '请先选择一个分类',
      importTodo: '导入功能开发中',
      exportTodo: '正在生成导出文件...',
      created: '字典项已创建',
      updated: '字典项已更新',
      deleted: '字典项已删除',
      typeCreated: '分类已创建',
      typeUpdated: '分类已更新',
      typeDeleted: '分类已删除',
      notSelected: '未选择',
      pageLabel: '页',
      totalLabel: '总计',
      currentType: '当前分类',
      dialogs: {
        addItemTitle: '新增字典项',
        editItemTitle: '编辑字典项',
        addTypeTitle: '新增分类',
        editTypeTitle: '编辑分类',
      },
      fields: {
        type: '分类',
        typeName: '分类名称',
        typeCode: '分类编码',
        label: '字典标签',
        value: '字典键值',
        sort: '排序',
        status: '状态',
        remark: '备注',
      },
      placeholders: {
        typeName: '例如：用户状态',
        typeCode: '例如：user_status',
        typeDesc: '请输入分类描述',
        label: '例如：启用',
        value: '例如：active',
        remark: '请输入备注说明',
      },
      validation: {
        required: '请填写必填项',
      },
      columns: {
        label: '字典标签',
        value: '字典键值',
        style: '样式预览',
        sort: '排序',
        remark: '备注',
      },
      actions: {
        editItem: '编辑项目',
      },
      emptyHint: '请选择左侧分类或新增字典项',
      importSuccess: '导入成功',
      exportSuccess: '导出成功',
    },
    menuManagement: {
      typeAll: '全部类型',
      typeDirectory: '目录',
      typeMenu: '菜单',
      typeButton: '按钮',
    },
    permissionManagement: {
      clickToCopy: '点击可全选复制',
      pageDescription: '管理系统细粒度的功能标识、数据权限及菜单关联，为安全审计提供基础支持。',
      batchDelete: '批量删除',
      searchPlaceholder: '搜索权限名称、标识、描述...',
      typePlaceholder: '权限类型',
      modulePlaceholder: '业务模块',
      typeAll: '所有类型',
      typeMenu: '菜单权限',
      typeOperation: '功能权限',
      typeData: '数据权限',
      moduleAll: '所有模块',
      importSuccess: '导入成功',
      exporting: '正在导出...',
      loadFailed: '加载权限失败',
      operation: '功能',
      menu: '菜单',
      data: '数据',
      code: '权限标识',
      name: '权限名称',
      type: '类型',
      module: '所属模块',
      description: '描述',
    },
    monitor: {
      pageTitle: '系统实时监控',
      pageDescription: '查看运行时状态、服务健康与关键资源信息。',
      refresh: '手动刷新',
      exportSnapshot: '导出快照',
      uptime: '运行时长',
      goroutines: 'Goroutines',
      goVersion: 'Go 版本',
      numCPU: 'CPU 核心数',
      memoryAlloc: '已分配内存',
      memorySys: '系统内存',
      heapAlloc: 'Heap Alloc',
      coreResourcesTitle: '核心资源监控',
      coreResourcesDesc: '实时监测系统核心硬件资源的波峰波谷',
      cpuUsage: 'CPU 使用率',
      memUsage: '内存使用率',
      diskUsage: '磁盘使用率',
      onlineUsers: '在线用户',
      systemUptime: '系统运行',
      serviceHealthTitle: '服务健康状况',
      allServicesRunning: '全服务正常运行中',
    },
    settingsPage: {
      description: '配置系统核心参数、安全策略及第三方集成服务。',
      tipsTitle: '快速提示',
      tipsDesc: '所有修改将在点击“立即同步”后实时生效于生产环境。',
      viewDocs: '查看详细文档',
      syncing: '正在同步系统配置...',
      syncSuccess: '系统配置已更新',
      syncFailed: '配置同步失败',
      resetInfo: '已还原所有未保存的更改',
      pendingSync: '检测到配置更改',
      pendingSyncCount: '项待同步',
      resetChanges: '重置更改',
      syncNow: '立即同步配置',
    },
    logs: {
      title: '统一日志审计',
      description: '系统登录、业务操作及高风险审计日志的统一查询与安全审计中心。',
      detailTitle: '日志详细审计',
      detailDesc: '详细记录本次操作的环境信息、业务细节及审计结果。',
      tabLogin: '登录',
      tabOperation: '操作',
      tabAudit: '审计',
      deviceBrowser: '设备 / 浏览器',
      batchDeleteSuccess: '日志已删除',
      searchPlaceholder: '搜索用户名、IP 或操作内容...',
      statusAll: '所有状态',
      deleteSelected: '删除所选',
      importTodo: '导入功能开发中',
      exporting: '正在生成导出文件...',
      onlyOperationCanClear: '仅支持清理操作日志',
      cleared: '操作日志已清理',
      stats: {
        total: '总条数',
      },
      columns: {
        user: '用户',
        time: '时间',
        ip: 'IP 地址',
        status: '状态',
        operation: '操作内容',
        error: '错误',
      },
      actions: {
        detail: '详情',
      },
      sections: {
        userEnv: '用户环境',
        bizAction: '业务动作',
        impactScope: '影响范围',
        detailNote: '详细描述 / 备注',
      },
      impact: {
        users: '影响 {count} 个用户',
        roles: '影响 {count} 个角色',
        authRefresh: '触发权限刷新',
        sessionRevoke: '强制会话失效',
      },
      fields: {
        username: '操作人',
        time: '发生时间',
        ip: 'IP 地址',
        location: '地理位置',
        module: '所属模块',
        operation: '操作内容',
        resource: '资源类型',
        resourceId: '资源 ID',
        resourceName: '资源名称',
        request: '请求',
        requestBody: '请求体',
        responseBody: '响应体',
        detail: '审计详情',
        duration: '耗时',
        device: '设备终端',
        browser: '浏览器',
        logoutTime: '退出时间',
      },
    },
  },
  settings: {
    basic: {
      title: '基础设置',
      description: '配置系统基础信息和全局参数',
      systemName: '系统名称',
      systemNameDesc: '显示在页面标题和登录页的系统名称',
      systemVersion: '系统版本',
      systemVersionDesc: '当前系统版本号',
      companyName: '公司名称',
      companyNameDesc: '显示在页脚的公司名称',
      systemUrl: '系统地址',
      systemUrlDesc: '系统访问的主要 URL 地址',
      timezone: '时区',
      timezoneDesc: '系统默认时区',
      dateFormat: '日期格式',
      dateFormatDesc: '日期显示格式',
    },
    security: {
      title: '安全设置',
      description: '配置系统安全策略和访问控制',
      passwordMinLength: '密码最小长度',
      passwordMinLengthDesc: '用户密码允许的最小字符数',
      passwordComplexity: '密码复杂度',
      passwordComplexityDesc: '要求密码包含大写、小写、数字和特殊字符',
      passwordExpireDays: '密码过期天数',
      passwordExpireDaysDesc: '密码必须更改的天数（0 表示永不过期）',
      sessionTimeout: '会话超时时间（分钟）',
      sessionTimeoutDesc: '空闲后自动退出的时间',
      maxLoginAttempts: '最大登录尝试次数',
      maxLoginAttemptsDesc: '失败达到指定次数后锁定账户',
      lockoutDuration: '锁定时长（分钟）',
      lockoutDurationDesc: '登录失败后的锁定时间',
      enableTwoFactor: '启用双因子认证',
      enableTwoFactorDesc: '启用二次验证',
      ipWhitelist: 'IP 白名单',
      ipWhitelistDesc: '允许访问的 IP 地址列表（每行一个）',
    },
    email: {
      title: '邮件设置',
      description: '配置系统邮件服务器',
      emailEnabled: '启用邮件服务',
      emailEnabledDesc: '启用系统邮件通知功能',
      smtpHost: 'SMTP 服务器',
      smtpHostDesc: '邮件服务器地址',
      smtpPort: 'SMTP 端口',
      smtpPortDesc: '邮件服务器端口号',
      smtpSsl: '启用 SSL/TLS',
      smtpSslDesc: '使用安全连接',
      smtpUsername: 'SMTP 用户名',
      smtpUsernameDesc: '邮件服务器登录账号',
      smtpPassword: 'SMTP 密码',
      smtpPasswordDesc: '邮件服务器登录密码',
      emailFrom: '发件人地址',
      emailFromDesc: '系统邮件的发件人地址',
      emailFromName: '发件人姓名',
      emailFromNameDesc: '系统邮件的发件人显示名称',
    },
    notification: {
      title: '通知设置',
      description: '配置系统通知和告警规则',
      notifyOnLogin: '登录通知',
      notifyOnLoginDesc: '用户登录时发送通知',
      notifyOnUserCreate: '用户创建通知',
      notifyOnUserCreateDesc: '创建新用户时发送通知',
      notifyOnPermissionChange: '权限变更通知',
      notifyOnPermissionChangeDesc: '用户权限变更时发送通知',
      notifyOnHostDown: '主机离线通知',
      notifyOnHostDownDesc: '主机离线时发送告警',
      notifyOnHighRisk: '高风险操作通知',
      notifyOnHighRiskDesc: '高风险操作时立即发送通知',
    },
    storage: {
      title: '存储设置',
      description: '配置数据存储和备份策略',
      logRetentionDays: '日志保留天数',
      logRetentionDaysDesc: '系统日志自动清理前保留的天数',
      backupEnabled: '自动备份',
      backupEnabledDesc: '启用数据库自动备份',
      backupFrequency: '备份频率',
      backupFrequencyDesc: '数据库备份的执行频率',
      backupRetentionCount: '备份保留数量',
      backupRetentionCountDesc: '保留的备份文件最大数量',
      uploadMaxSize: '最大上传大小（MB）',
      uploadMaxSizeDesc: '单个文件上传的最大大小',
    },
    actions: {
      save: '保存设置',
      reset: '重置',
      saved: '已保存',
      resetSuccess: '已重置为默认值',
      required: '必填',
      readonly: '只读',
      enabled: '启用',
      disabled: '禁用',
    },
  },
  sysMonitor: {
    cpu: 'CPU 使用率',
    memory: '内存使用率',
    disk: '磁盘使用率',
    network: '网络流量',
    database: '数据库',
    activeUsers: '活跃用户',
    uptime: '运行时长',
    upload: '上传速度',
    download: '下载速度',
    connections: '连接数',
    systemInfo: '系统信息',
    cpuCores: 'CPU 核心使用率',
    core: '核心',
  },
  actions: {
    add: '新增',
    edit: '编辑',
    delete: '删除',
    detail: '详情',
    search: '搜索',
    export: '导出',
    import: '导入',
    refresh: '刷新',
    filter: '筛选',
  },
  status: {
    enabled: '启用',
    disabled: '禁用',
    active: '激活',
    inactive: '停用',
    online: '在线',
    offline: '离线',
    running: '运行中',
    stopped: '已停止',
    warning: '警告',
    healthy: '健康',
    error: '异常',
    success: '成功',
    failed: '失败',
    scheduled: '已计划',
    completed: '已完成',
  },
  user: {
    username: '用户名',
    password: '密码',
    realName: '姓名',
    email: '邮箱',
    phone: '手机号',
    department: '部门',
    position: '岗位',
    role: '角色',
    status: '状态',
    login: '登录',
    logout: '退出',
    profile: '个人资料',
    changePassword: '修改密码',
  },
  login: {
    title: '登录',
    subtitle: '欢迎使用系统',
    username: '用户名',
    password: '密码',
    rememberPassword: '记住密码',
    forgotPassword: '忘记密码',
    loginButton: '登录',
    loggingIn: '登录中...',
    otherLoginMethods: '其他登录方式',
    testAccount: '测试账号',
    copyright: '版权所有',
    version: '版本',
    usernamePlaceholder: '请输入用户名',
    passwordPlaceholder: '请输入密码',
    usernameRequired: '用户名不能为空',
    passwordRequired: '密码不能为空',
    loginSuccess: '登录成功',
    loginError: '登录异常',
    loginFailed: '登录失败',
    carousel: {
      item1: {
        title: '强大的主机管理',
        subtitle: '集中管理所有服务器资源',
        description: '支持多云环境，轻松监控和管理成千上万台服务器',
      },
      item2: {
        title: 'K8s 集群编排',
        subtitle: '简化容器编排与部署',
        description: '可视化管理 Kubernetes 集群，一键部署应用',
      },
      item3: {
        title: '智能监控与告警',
        subtitle: '实时监控系统状态',
        description: '智能告警策略，第一时间发现并处理问题',
      },
      item4: {
        title: '安全权限管理',
        subtitle: '企业级安全保障',
        description: '细粒度权限控制，完整审计日志追踪',
      },
    },
  },
  validation: {
    required: '此项为必填项',
    invalidEmail: '邮箱格式不正确',
    invalidPhone: '手机号格式不正确',
    minLength: '至少输入 {min} 个字符',
    maxLength: '最多输入 {max} 个字符',
  },
  profile: {
    title: '个人中心',
    personalInfo: '个人信息',
    security: '安全设置',
    notifications: '通知设置',
    preferences: '偏好设置',
    loginHistory: '登录历史',
    accountSettings: '账号设置',
    avatar: '头像',
    basicInfo: '基本信息',
    contactInfo: '联系信息',
    personalSettings: '个人设置',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    emailNotification: '邮件通知',
    systemNotification: '系统通知',
    theme: '主题',
    language: '语言',
    timezone: '时区',
    dateFormat: '日期格式',
    loginTime: '登录时间',
    ipAddress: 'IP 地址',
    device: '设备',
    location: '位置',
    browser: '浏览器',
    os: '操作系统',
  },
  modules: {
    dashboard: {
      title: '仪表盘',
      description: '系统概览',
      totalHosts: '主机总数',
      k8sClusters: 'K8s 集群数',
      runningServices: '运行中的服务',
      alertCount: '告警数量',
      systemAlerts: '系统告警',
      lastUpdate: '最后更新',
      recentActivities: '最近活动',
      viewAll: '查看全部',
      comparedToYesterday: '较昨日',
      activities: {
        addHost: '添加主机',
        deployApp: '部署应用',
        scaleCluster: '扩展集群',
        systemUpdate: '系统更新',
      },
      alerts: {
        cpuWarning: 'CPU 使用率超过 80%',
        nodeUnavailable: '节点不可用',
        storageWarning: '存储使用率达到 70%',
      },
    },
    host: {
      title: '主机管理',
      description: '管理和监控所有主机资源',
      addHostTitle: '添加主机',
      addHostDescription: '填写主机信息并加入管理系统',
      confirmAdd: '确认',
      hostname: '主机名',
      ipAddress: 'IP 地址',
      status: '状态',
      cpuUsage: 'CPU 使用率',
      memoryUsage: '内存使用率',
      diskUsage: '磁盘使用率',
      os: '操作系统',
      location: '位置',
      addHost: '添加主机',
      editHost: '编辑主机',
      deleteHost: '删除主机',
      remoteConnect: '远程连接',
      configManage: '配置管理',
      restart: '重启',
    },
    k8s: {
      title: 'K8s 集群',
      description: '管理 Kubernetes 集群与资源',
      clusterList: '集群列表',
      clusterListTitle: 'K8s 集群列表',
      clusterListDescription: '查看并管理所有 Kubernetes 集群',
      nodeManagement: '节点管理',
      nodeManagementTitle: 'K8s 节点管理',
      nodeManagementDescription: '查看并管理 Kubernetes 集群节点',
      workloads: '工作负载',
      workloadsTitle: 'K8s 工作负载',
      workloadsDescription: '管理 Deployment、Pod 及相关资源',
      networkServicesTitle: 'K8s 网络服务',
      networkServicesDescription: '管理 Service 和网络配置',
      routingTitle: 'K8s 应用路由',
      routingDescription: '管理 Ingress 和应用路由配置',
      addCluster: '添加集群',
      addClusterTitle: '添加 K8s 集群',
      addClusterDescription: '配置新的 Kubernetes 集群连接',
      confirmAdd: '确认',
      clusterName: '集群名称',
      version: '版本',
      nodeCount: '节点数',
      deletePod: '删除 Pod',
      deletePodDescription: '确认删除该 Pod 吗？删除后会终止并从集群中移除。',
      deleteDeployment: '删除 Deployment',
      deleteDeploymentDescription: '确认删除该 Deployment 吗？其关联的 Pod 也会一并删除。',
      deleteService: '删除 Service',
      deleteServiceDescription: '确认删除该 Service 吗？这可能会影响相关应用的网络访问。',
      scale: '扩缩容',
      accessService: '访问服务',
      // 集群表单字段
      k8sVersion: 'K8s 版本',
      resourceCount: '资源数量',
      k8sClusterManagement: 'K8s 集群管理',
      clusterNameLabel: '集群名称',
      clusterNamePlaceholder: '请输入集群名称',
      k8sVersionLabel: 'K8s 版本',
      selectVersion: '选择版本',
      apiServerAddress: 'API Server 地址',
      authMethod: '认证方式',
      accessToken: '访问令牌',
      tokenPlaceholder: '请输入访问令牌',
      datacenterLocation: '数据中心位置',
      selectDatacenter: '选择数据中心',
      environmentType: '环境类型',
      selectEnvironment: '选择环境',
      defaultNamespace: '默认命名空间',
      clusterDescription: '集群描述',
      descriptionPlaceholder: '请输入集群描述',
      viewDetails: '查看详情',
      upgradeCluster: '升级集群',
      expandNodes: '扩容节点',
      configManagement: '配置管理',
      deleteCluster: '删除集群',
      searchClusterPlaceholder: '搜索集群',
      nodeCountLabel: '节点数量',
      podCount: 'Pod 数量',
      podCountLabel: 'Pod 数量',
      cpuUsageLabel: 'CPU 使用率',
      memoryUsageLabel: '内存使用率',
      datacenterLabel: '数据中心',
      evictPod: '驱逐 Pod',
      setTaint: '设置污点',
      deleteNode: '删除节点',
      searchNodePlaceholder: '搜索节点',
      nodeName: '节点名称',
      role: '角色',
      operations: '操作',
      podDeleted: 'Pod 已删除',
      podRestarted: 'Pod 已重启',
      status: '状态',
      cpuUsage: 'CPU 使用率',
      memoryUsage: '内存使用率',
      // Pod 列表字段
      podName: 'Pod 名称',
      namespace: '命名空间',
      cluster: '集群',
      node: '节点',
      containers: '容器数',
      restartCount: '重启次数',
      runningTime: '运行时间',
      searchPodPlaceholder: '搜索 Pod',
      clusterFilter: '集群筛选',
      allClusters: '所有集群',
      namespaceFilter: '命名空间筛选',
      allNamespaces: '所有命名空间',
      statusFilter: '状态筛选',
      allStatus: '全部状态',
      totalPods: 'Pod 总数',
      podRunning: '运行中 Pod',
      podPending: '等待中 Pod',
      podFailed: '失败 Pod',
      podSucceeded: '成功 Pod',
      podUnknown: '未知 Pod',
      podStatusRunning: '运行中',
      podStatusPending: '等待中',
      podStatusSucceeded: '成功',
      podStatusFailed: '失败',
      podStatusUnknown: '未知',
      containerCount: '容器数量',
      containerReady: '容器就绪数',
    },
    deploy: {
      title: '组件部署',
      description: '部署系统组件',
      componentLibrary: '组件库',
      deployHistory: '部署历史',
      deploy: '部署',
      rollback: '回滚',
      startDeploy: '开始部署',
      availableComponents: '可用组件',
      searchComponents: '搜索组件',
      deploymentTarget: '部署目标',
      progressComplete: '进度完成',
      target: '目标',
      completed: '已完成',
      categories: {
        basic: '基础',
        database: '数据库',
        container: '容器',
        monitor: '监控',
        security: '安全',
      },
      components: {
        nginx: {
          name: 'Nginx',
          description: '高性能 HTTP 和反向代理服务器',
        },
        mysql: {
          name: 'MySQL',
          description: '关系型数据库管理系统',
        },
        redis: {
          name: 'Redis',
          description: '内存数据结构存储系统',
        },
        docker: {
          name: 'Docker',
          description: '容器化平台',
        },
        prometheus: {
          name: 'Prometheus',
          description: '开源监控系统和时序数据库',
        },
        vault: {
          name: 'Vault',
          description: '安全存储和管理敏感数据',
        },
      },
      status: {
        success: '成功',
        running: '运行中',
        failed: '失败',
      },
      time: {
        minutesAgo: '分钟前',
        inProgress: '进行中',
        hoursAgo: '小时前',
      },
    },
    monitor: {
      title: '监控',
      description: '系统监控',
      alertRules: '告警规则',
      alertHistory: '告警历史',
      notificationSettings: '通知设置',
      monitorDashboard: '监控看板',
    },
    operations: {
      title: '运维监控',
      description: '系统运维监控',
      realTimeMonitoring: '实时监控',
      systemLogs: '系统日志',
      opsTasks: '运维任务',
      alertCenter: '告警中心',
      realTimeLogs: '实时日志',
      opsTaskList: '任务列表',
      alertRecords: '告警记录',
      filter: '筛选',
      export: '导出',
      createTask: '创建任务',
      loadMoreLogs: '加载更多日志',
      alertSettings: '告警设置',
      viewDetails: '查看详情',
      markAsRead: '标记为已读',
      progress: '进度',
      host: '主机',
      startTime: '开始时间',
      metrics: {
        cpuAvgUsage: 'CPU 平均使用率',
        memoryAvgUsage: '内存平均使用率',
        diskUsage: '磁盘使用率',
        networkTraffic: '网络流量',
      },
      status: {
        running: '运行中',
        completed: '已完成',
        scheduled: '已计划',
      },
      tasks: {
        batchUpdateHosts: '批量更新主机',
        databaseBackup: '数据库备份',
        cleanTempFiles: '清理临时文件',
      },
      alerts: {
        cpuAlert: 'CPU 告警',
        nodeUnavailable: '节点不可用',
        diskSpaceAlert: '磁盘空间告警',
      },
    },
  },
};

type Translations = typeof zhTranslations;

const enTranslations: Translations = {
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    all: 'All',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    view: 'View',
    search: 'Search',
    reset: 'Reset',
    submit: 'Submit',
    back: 'Back',
    next: 'Next',
    close: 'Close',
    copy: 'Copy',
    loading: 'Loading...',
    noData: 'No Data',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    actions: 'Actions',
    remark: 'Remark',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    time: 'Time',
    logTime: 'Log Time',
    pleaseLogin: 'Please log in first',
    permissionDenied: 'Permission denied',
    roleDenied: 'Insufficient role permissions',
    noPermissionTitle: 'Access Denied',
    noPermissionHint: 'Sorry, you do not have permission to access this page. Please contact an administrator.',
  },
  systemManage: {
    importExport: {
      importTitle: 'Import Data',
      exportTitle: 'Export Data',
      supportFiles: 'Supports .xlsx, .csv files',
      exportFormat: 'Export Format',
      clickToUpload: 'Click to upload',
      dragAndDrop: 'or drag and drop',
      maxSize: 'Max size 10MB',
      downloadTemplate: 'Download Template',
      processing: 'Processing...',
      exportAll: 'Export All Data',
      exportSelected: 'Export Selected Data',
      error: 'Invalid file format. Please upload Excel or CSV.',
      importSuccess: 'Successfully imported {count} records',
    },
  },
  system: {
    title: 'Pantheon',
    subtitle: 'Enterprise Operations Platform',
    admin: 'Admin',
    adminEmail: 'admin@example.com',
    addMenuTitle: 'Add Menu',
    addMenuDescription: 'Create new system menu or button permission',
    addRoleTitle: 'Add Role',
    addRoleDescription: 'Create new system role and configure menu permissions',
    addUserTitle: 'Add User',
    addUserDescription: 'Create new system user',
  },
  topBar: {
    searchPlaceholder: 'Search...',
    theme: 'Theme',
    language: 'Language',
    languageChinese: 'Chinese',
    languageEnglish: 'English',
    notifications: 'Notifications',
    myAccount: 'My Account',
    profile: 'Profile',
    profileCenter: 'Profile Center',
    accountSettings: 'Settings',
    logout: 'Logout',
    noNewNotifications: 'No new notifications',
  },
  notification: {
    inbox: 'Inbox',
    templates: 'Templates',
  },
  footer: {
    copyright: 'Pantheon Platform',
    database: 'Database',
    cache: 'Cache',
    systemStatus: 'System Running',
    normal: 'Normal',
    error: 'Error',
  },
  menu: {
    dashboard: 'Dashboard',
    systemOverview: 'System Overview',
    hosts: 'Hosts',
    k8s: 'K8s',
    k8sClusters: 'K8s Clusters',
    k8sNodes: 'K8s Nodes',
    k8sWorkloads: 'K8s Workloads',
    k8sNetwork: 'K8s Network',
    k8sRouting: 'K8s Routing',
    deploy: 'Deploy',
    operations: 'Operations',
    alert: 'Monitoring',
    alertMonitor: 'Monitor',
    alertManagement: 'Alert Management',
    alertRules: 'Alert Rules',
    alertHistory: 'Alert History',
    alertNotification: 'Notification Settings',
    system: 'System',
    systemUsers: 'Users',
    systemDepartments: 'Departments',
    systemPositions: 'Positions',
    systemRoles: 'Roles',
    systemMenus: 'Menus',
    systemPermissions: 'Permissions',
    systemLogs: 'Logs',
    systemAudit: 'Audit',
    systemSettings: 'Settings',
    systemDictionary: 'Dictionary',
    systemMonitor: 'System Monitor',
    systemLogManagement: 'Log Management',
    profile: 'Profile',
    tenantManagement: 'Tenant Management',
  },
  systemManagement: {
    title: 'System Management',
    description: 'Manage system users, permissions and configurations',
    permissionMatrix: 'Permission Matrix',
    permissionAudit: 'Permission Audit',
    loginLogs: 'Login Logs',
    dashboard: {
      location: 'Shanghai, China',
      greetings: {
        morning: 'Good morning',
        afternoon: 'Good afternoon',
        evening: 'Good evening',
      },
      adminFallback: 'Admin',
      welcomeBack: 'Welcome back to Pantheon Admin',
      currentDate: 'Current Date',
      quickActions: {
        addUser: 'Add User',
        authorizeRole: 'Role Authorization',
        configureMenu: 'Menu Configuration',
        manageDictionary: 'Dictionary',
        auditLogs: 'Audit Logs',
        databaseBackup: 'Database Backup',
      },
    },
    roles: {
      usersDialog: {
        title: 'Role Members',
        description: 'Add or remove members to keep the role membership up to date.',
        tabCurrent: 'Current',
        tabAdd: 'Add',
        searchPlaceholder: 'Search by name, username, or email...',
        selectedLabel: 'Selected',
        emptyCurrent: 'No members in this role',
        emptySearch: 'No matching users found',
        removeSelected: 'Remove Selected',
        addSelected: 'Add Selected',
        removeSuccess: 'Members removed',
        addSuccess: 'Members added',
      },
    },
    users: {
      actions: {
        assignRoles: 'Assign Roles',
        resetPassword: 'Reset Password',
      },
      permissionsPanel: {
        title: 'User Permissions',
        description: 'View the aggregated permissions (from roles via Casbin policies).',
        total: 'Total',
        searchPlaceholder: 'Search permissions...',
        verifyTitle: 'Verify Permission',
        verifyHint: 'Type a permission string to verify (e.g. /api/v1/system/users:get)',
        verifyPlaceholder: 'Enter permission',
        verifyButton: 'Verify',
        verifyHas: 'User has this permission',
        verifyNot: 'User does not have this permission',
      },
      roleAssignDialog: {
        title: 'Assign Roles',
        description: 'Assign or remove roles for the user',
        selectRoles: 'Select roles for this user',
        systemRole: 'System',
        customRole: 'Custom',
        setExpiry: 'Set expiry',
        expiryPlaceholder: 'Select expiry date',
        updated: 'Roles updated',
        updateFailed: 'Failed to update roles',
        tipAssignPrefix: 'Will assign',
        tipRoleSuffix: 'role(s)',
        tipUntil: 'until',
        rolesLabel: 'Select roles',
        searchPlaceholder: 'Search roles...',
      },
      form: {
        usernamePlaceholder: 'Enter username',
        realNamePlaceholder: 'Enter name',
        emailPlaceholder: 'Enter email',
        phonePlaceholder: 'Enter phone',
        passwordPlaceholder: 'Enter password',
        departmentPlaceholder: 'Select department',
        rolePlaceholder: 'Select role',
        remarkPlaceholder: 'Enter remark',
      },
    },
    positions: {
      level: 'Level',
      levelAll: 'All Levels',
      levelL1: 'L1',
      levelL2: 'L2',
      levelL3: 'L3',
    },
    dictionary: {
      typeTitle: 'Types',
      typeSearchPlaceholder: 'Search types...',
      typeEmptyHint: 'No matching types',
      searchPlaceholder: 'Search dictionary items...',
      addItem: 'Add Item',
      typeKey: 'Type Key',
      unselected: 'Unselected',
      refresh: 'Refresh',
      addCategoryTodo: 'Add type is not implemented',
      selectTypeFirst: 'Please select a type first',
      importTodo: 'Import is not implemented',
      exportTodo: 'Generating export file...',
      created: 'Item created',
      updated: 'Item updated',
      deleted: 'Item deleted',
      typeCreated: 'Type created',
      typeUpdated: 'Type updated',
      typeDeleted: 'Type deleted',
      pageLabel: 'Page',
      totalLabel: 'Total',
      currentType: 'Current Type',
      dialogs: {
        addItemTitle: 'Add Dictionary Item',
        editItemTitle: 'Edit Dictionary Item',
        addTypeTitle: 'Add Type',
        editTypeTitle: 'Edit Type',
      },
      fields: {
        type: 'Type',
        typeName: 'Type Name',
        typeCode: 'Type Code',
        label: 'Label',
        value: 'Value',
        sort: 'Sort',
        status: 'Status',
        remark: 'Remark',
      },
      placeholders: {
        typeName: 'e.g. User Status',
        typeCode: 'e.g. user_status',
        typeDesc: 'Enter type description',
        label: 'e.g. Active',
        value: 'e.g. active',
        remark: 'Enter remark',
      },
      validation: {
        required: 'Please fill required fields',
      },
      columns: {
        label: 'Label',
        value: 'Value',
        style: 'Style Preview',
        sort: 'Sort',
        remark: 'Remark',
      },
      actions: {
        editItem: 'Edit Item',
      },
      emptyHint: 'Select a type from the left or add a new item',
      importSuccess: 'Imported successfully',
      exportSuccess: 'Exported successfully',
    },
    menuManagement: {
      typeAll: 'All Types',
      typeDirectory: 'Directory',
      typeMenu: 'Menu',
      typeButton: 'Button',
    },
    permissionManagement: {
      clickToCopy: 'Click to select and copy',
      pageDescription: 'Manage permission identifiers, data scope, and menu bindings for auditing.',
      batchDelete: 'Batch Delete',
      searchPlaceholder: 'Search name, code, or description...',
      typePlaceholder: 'Type',
      modulePlaceholder: 'Module',
      typeAll: 'All Types',
      typeMenu: 'Menu',
      typeOperation: 'Operation',
      typeData: 'Data',
      moduleAll: 'All Modules',
      importSuccess: 'Import succeeded',
      exporting: 'Exporting...',
      loadFailed: 'Failed to load permissions',
      operation: 'Operation',
      menu: 'Menu',
      data: 'Data',
      code: 'Permission Code',
      name: 'Permission Name',
      type: 'Type',
      module: 'Module',
      description: 'Description',
    },
    monitor: {
      pageTitle: 'System Monitor',
      pageDescription: 'Runtime status, service health, and key resource information.',
      refresh: 'Refresh',
      exportSnapshot: 'Export Snapshot',
      uptime: 'Uptime',
      goroutines: 'Goroutines',
      goVersion: 'Go Version',
      numCPU: 'CPU Cores',
      memoryAlloc: 'Alloc',
      memorySys: 'Sys',
      heapAlloc: 'Heap Alloc',
      coreResourcesTitle: 'Core Resource Monitor',
      coreResourcesDesc: 'Track core resource usage trends in real time',
      cpuUsage: 'CPU Usage',
      memUsage: 'Memory Usage',
      diskUsage: 'Disk Usage',
      onlineUsers: 'Online Users',
      systemUptime: 'Uptime',
      serviceHealthTitle: 'Service Health',
      allServicesRunning: 'All services are running',
    },
    settingsPage: {
      description: 'Configure core parameters, security policies, and integrations.',
      tipsTitle: 'Quick Tip',
      tipsDesc: 'Changes take effect after you click Sync Now.',
      viewDocs: 'View Documentation',
      syncing: 'Syncing settings...',
      syncSuccess: 'Settings updated',
      syncFailed: 'Settings sync failed',
      resetInfo: 'Reverted all unsaved changes',
      pendingSync: 'Detected configuration changes',
      pendingSyncCount: 'items pending sync',
      resetChanges: 'Reset Changes',
      syncNow: 'Sync Now',
    },
    logs: {
      title: 'Unified Log Audit',
      description: 'Unified query center for login, operation, and high-risk audit records.',
      detailTitle: 'Log Details',
      detailDesc: 'This record contains environment data, operation details, and audit results.',
      tabLogin: 'Login',
      tabOperation: 'Operation',
      tabAudit: 'Audit',
      deviceBrowser: 'Device / Browser',
      batchDeleteSuccess: 'Logs deleted',
      searchPlaceholder: 'Search by username, IP, or operation summary...',
      statusAll: 'All Status',
      deleteSelected: 'Delete Selected',
      importTodo: 'Import is not implemented',
      exporting: 'Generating export file...',
      onlyOperationCanClear: 'Only operation logs can be cleared',
      cleared: 'Operation logs cleared',
      stats: {
        total: 'Total',
      },
      columns: {
        user: 'User',
        time: 'Time',
        ip: 'IP',
        status: 'Status',
        operation: 'Operation',
        error: 'Error',
      },
      actions: {
        detail: 'Details',
      },
      sections: {
        userEnv: 'User Environment',
        bizAction: 'Business Action',
        impactScope: 'Impact Scope',
        detailNote: 'Details / Notes',
      },
      impact: {
        users: 'Affects {count} users',
        roles: 'Affects {count} roles',
        authRefresh: 'Refresh auth snapshot',
        sessionRevoke: 'Revoke active sessions',
      },
      fields: {
        username: 'User',
        time: 'Time',
        ip: 'IP',
        location: 'Location',
        module: 'Module',
        operation: 'Operation',
        resource: 'Resource',
        resourceId: 'Resource ID',
        resourceName: 'Resource Name',
        request: 'Request',
        requestBody: 'Request Body',
        responseBody: 'Response Body',
        detail: 'Audit Detail',
        duration: 'Duration',
        device: 'Device',
        browser: 'Browser',
        logoutTime: 'Logout Time',
      },
    },
  },
  settings: {
    basic: {
      title: 'Basic Settings',
      description: 'Configure basic system information and global parameters',
      systemName: 'System Name',
      systemNameDesc: 'System name displayed on page title and login page',
      systemVersion: 'System Version',
      systemVersionDesc: 'Current system version number',
      companyName: 'Company Name',
      companyNameDesc: 'Company name displayed in footer',
      systemUrl: 'System URL',
      systemUrlDesc: 'Main URL address for system access',
      timezone: 'Timezone',
      timezoneDesc: 'Default system timezone',
      dateFormat: 'Date Format',
      dateFormatDesc: 'Format for displaying dates',
    },
    security: {
      title: 'Security Settings',
      description: 'Configure system security policies and access control',
      passwordMinLength: 'Min Password Length',
      passwordMinLengthDesc: 'Minimum number of characters for user password',
      passwordComplexity: 'Password Complexity',
      passwordComplexityDesc: 'Require password to contain uppercase, lowercase, numbers and special characters',
      passwordExpireDays: 'Password Expiration Days',
      passwordExpireDaysDesc: 'Days before password must be changed (0 for no expiration)',
      sessionTimeout: 'Session Timeout (min)',
      sessionTimeoutDesc: 'Time before auto logout after inactivity',
      maxLoginAttempts: 'Max Login Attempts',
      maxLoginAttemptsDesc: 'Lock account after this many failed attempts',
      lockoutDuration: 'Lockout Duration (min)',
      lockoutDurationDesc: 'Time to unlock after failed login lockout',
      enableTwoFactor: 'Enable 2FA',
      enableTwoFactorDesc: 'Enable Two-Factor Authentication',
      ipWhitelist: 'IP Whitelist',
      ipWhitelistDesc: 'List of allowed IP addresses (one per line)',
    },
    email: {
      title: 'Email Settings',
      description: 'Configure system email server',
      emailEnabled: 'Enable Email Service',
      emailEnabledDesc: 'Enable system email notification function',
      smtpHost: 'SMTP Server',
      smtpHostDesc: 'Mail server address',
      smtpPort: 'SMTP Port',
      smtpPortDesc: 'Mail server port number',
      smtpSsl: 'Enable SSL/TLS',
      smtpSslDesc: 'Use secure connection',
      smtpUsername: 'SMTP Username',
      smtpUsernameDesc: 'Mail server login account',
      smtpPassword: 'SMTP Password',
      smtpPasswordDesc: 'Mail server login password',
      emailFrom: 'Sender Address',
      emailFromDesc: 'System email sender address',
      emailFromName: 'Sender Name',
      emailFromNameDesc: 'System email sender display name',
    },
    notification: {
      title: 'Notification Settings',
      description: 'Configure system notifications and alert rules',
      notifyOnLogin: 'Login Notification',
      notifyOnLoginDesc: 'Send notification on user login',
      notifyOnUserCreate: 'User Create Notification',
      notifyOnUserCreateDesc: 'Send notification when new user is created',
      notifyOnPermissionChange: 'Permission Change Notification',
      notifyOnPermissionChangeDesc: 'Send notification when user permissions change',
      notifyOnHostDown: 'Host Down Notification',
      notifyOnHostDownDesc: 'Send alert when host goes offline',
      notifyOnHighRisk: 'High Risk Notification',
      notifyOnHighRiskDesc: 'Send immediate notification on high risk operations',
    },
    storage: {
      title: 'Storage Settings',
      description: 'Configure data storage and backup policies',
      logRetentionDays: 'Log Retention Days',
      logRetentionDaysDesc: 'Days to keep system logs before auto cleanup',
      backupEnabled: 'Auto Backup',
      backupEnabledDesc: 'Enable database auto backup',
      backupFrequency: 'Backup Frequency',
      backupFrequencyDesc: 'Frequency of database backups',
      backupRetentionCount: 'Backup Retention Count',
      backupRetentionCountDesc: 'Maximum number of backup files to keep',
      uploadMaxSize: 'Max Upload Size (MB)',
      uploadMaxSizeDesc: 'Maximum size for single file upload',
    },
    actions: {
      save: 'Save Settings',
      reset: 'Reset',
      saved: 'Saved',
      resetSuccess: 'Reset to default values',
      required: 'Required',
      readonly: 'Read-only',
      enabled: 'Enabled',
      disabled: 'Disabled',
    },
  },
  sysMonitor: {
    cpu: 'CPU Usage',
    memory: 'Memory Usage',
    disk: 'Disk Usage',
    network: 'Network Traffic',
    database: 'Database',
    activeUsers: 'Active Users',
    uptime: 'Uptime',
    upload: 'Upload Speed',
    download: 'Download Speed',
    connections: 'Connections',
    systemInfo: 'System Info',
    cpuCores: 'CPU Core Usage',
    core: 'Core',
  },
  actions: {
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    detail: 'Detail',
    search: 'Search',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    filter: 'Filter',
  },
  status: {
    enabled: 'Enabled',
    disabled: 'Disabled',
    active: 'Active',
    inactive: 'Inactive',
    online: 'Online',
    offline: 'Offline',
    running: 'Running',
    stopped: 'Stopped',
    warning: 'Warning',
    healthy: 'Healthy',
    error: 'Error',
    success: 'Success',
    failed: 'Failed',
    scheduled: 'Scheduled',
    completed: 'Completed',
  },
  user: {
    username: 'Username',
    password: 'Password',
    realName: 'Name',
    email: 'Email',
    phone: 'Phone',
    department: 'Department',
    position: 'Position',
    role: 'Role',
    status: 'Status',
    login: 'Login',
    logout: 'Logout',
    profile: 'Profile',
    changePassword: 'Change Password',
  },
  login: {
    title: 'Login',
    subtitle: 'Welcome',
    username: 'Username',
    password: 'Password',
    rememberPassword: 'Remember',
    forgotPassword: 'Forgot',
    loginButton: 'Login',
    loggingIn: 'Logging in...',
    otherLoginMethods: 'Other methods',
    testAccount: 'Test Account',
    copyright: 'Copyright',
    version: 'Version',
    usernamePlaceholder: 'Enter username',
    passwordPlaceholder: 'Enter password',
    usernameRequired: 'Username required',
    passwordRequired: 'Password required',
    loginSuccess: 'Login successful',
    loginError: 'Login error',
    loginFailed: 'Login failed',
    carousel: {
      item1: {
        title: 'Powerful Host Management',
        subtitle: 'Centralize all your server resources',
        description: 'Support multi-cloud environments, easily monitor and manage thousands of servers',
      },
      item2: {
        title: 'K8s Cluster Orchestration',
        subtitle: 'Simplify container orchestration and deployment',
        description: 'Visually manage Kubernetes clusters, one-click application deployment',
      },
      item3: {
        title: 'Smart Monitoring & Alerts',
        subtitle: 'Real-time system status monitoring',
        description: 'Intelligent alert strategies to detect and resolve issues immediately',
      },
      item4: {
        title: 'Secure Permission Management',
        subtitle: 'Enterprise-grade security assurance',
        description: 'Fine-grained permission control, complete audit log tracking',
      },
    },
  },
  validation: {
    required: 'Required',
    invalidEmail: 'Invalid email',
    invalidPhone: 'Invalid phone',
    minLength: 'Min {min} chars',
    maxLength: 'Max {max} chars',
  },
  profile: {
    title: 'Profile',
    personalInfo: 'Personal',
    security: 'Security',
    notifications: 'Notifications',
    preferences: 'Preferences',
    loginHistory: 'Login History',
    accountSettings: 'Settings',
    avatar: 'Avatar',
    basicInfo: 'Basic Info',
    contactInfo: 'Contact',
    personalSettings: 'Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    emailNotification: 'Email',
    systemNotification: 'System',
    theme: 'Theme',
    language: 'Language',
    timezone: 'Timezone',
    dateFormat: 'Date Format',
    loginTime: 'Login Time',
    ipAddress: 'IP Address',
    device: 'Device',
    location: 'Location',
    browser: 'Browser',
    os: 'OS',
  },
  modules: {
    dashboard: {
      title: 'Dashboard',
      description: 'System Overview',
      totalHosts: 'Total Hosts',
      k8sClusters: 'K8s Clusters',
      runningServices: 'Running Services',
      alertCount: 'Alert Count',
      systemAlerts: 'System Alerts',
      lastUpdate: 'Last Update',
      recentActivities: 'Recent Activities',
      viewAll: 'View All',
      comparedToYesterday: 'Compared to Yesterday',
      activities: {
        addHost: 'Add Host',
        deployApp: 'Deploy App',
        scaleCluster: 'Scale Cluster',
        systemUpdate: 'System Update',
      },
      alerts: {
        cpuWarning: 'CPU usage over 80%',
        nodeUnavailable: 'Node unavailable',
        storageWarning: 'Storage usage reached 70%',
      }
    },
    host: {
      title: 'Host Management',
      description: 'Manage and monitor all host resources',
      addHostTitle: 'Add Host',
      addHostDescription: 'Fill in host information to add to management system',
      confirmAdd: 'Confirm',
      hostname: 'Hostname',
      ipAddress: 'IP Address',
      status: 'Status',
      cpuUsage: 'CPU Usage',
      memoryUsage: 'Memory Usage',
      diskUsage: 'Disk Usage',
      os: 'OS',
      location: 'Location',
      addHost: 'Add Host',
      editHost: 'Edit Host',
      deleteHost: 'Delete Host',
      remoteConnect: 'Remote Connect',
      configManage: 'Config Manage',
      restart: 'Restart',
    },
    k8s: {
      title: 'K8s Clusters',
      description: 'Manage Kubernetes clusters and resources',
      clusterList: 'Cluster List',
      clusterListTitle: 'K8s Cluster List',
      clusterListDescription: 'View and manage all Kubernetes clusters',
      nodeManagement: 'Node Management',
      nodeManagementTitle: 'K8s Node Management',
      nodeManagementDescription: 'View and manage Kubernetes cluster nodes',
      workloads: 'Workloads',
      workloadsTitle: 'K8s Workloads',
      workloadsDescription: 'Manage Deployments, Pods and related resources',
      networkServicesTitle: 'K8s Network Services',
      networkServicesDescription: 'Manage Services and network configuration',
      routingTitle: 'K8s Application Routing',
      routingDescription: 'Manage Ingress and application routing configuration',
      addCluster: 'Add Cluster',
      addClusterTitle: 'Add K8s Cluster',
      addClusterDescription: 'Configure new Kubernetes cluster connection',
      confirmAdd: 'Confirm',
      clusterName: 'Cluster Name',
      version: 'Version',
      nodeCount: 'Node Count',
      deletePod: 'Delete Pod',
      deletePodDescription: 'Are you sure you want to delete this Pod? It will be terminated and removed from the cluster.',
      deleteDeployment: 'Delete Deployment',
      deleteDeploymentDescription: 'Are you sure you want to delete this Deployment? All associated Pods will also be deleted.',
      deleteService: 'Delete Service',
      deleteServiceDescription: 'Are you sure you want to delete this Service? This may affect network access to related applications.',
      scale: 'Scale',
      accessService: 'Access Service',
      // Cluster form fields
      k8sVersion: 'K8s Version',
      resourceCount: 'Resource Count',
      k8sClusterManagement: 'K8s Cluster Management',
      clusterNameLabel: 'Cluster Name',
      clusterNamePlaceholder: 'Enter cluster name',
      k8sVersionLabel: 'K8s Version',
      selectVersion: 'Select Version',
      apiServerAddress: 'API Server Address',
      authMethod: 'Auth Method',
      accessToken: 'Access Token',
      tokenPlaceholder: 'Enter access token',
      datacenterLocation: 'Datacenter Location',
      selectDatacenter: 'Select Datacenter',
      environmentType: 'Environment Type',
      selectEnvironment: 'Select Environment',
      defaultNamespace: 'Default Namespace',
      clusterDescription: 'Cluster Description',
      descriptionPlaceholder: 'Enter cluster description',
      viewDetails: 'View Details',
      upgradeCluster: 'Upgrade Cluster',
      expandNodes: 'Expand Nodes',
      configManagement: 'Config Management',
      deleteCluster: 'Delete Cluster',
      searchClusterPlaceholder: 'Search cluster',
      nodeCountLabel: 'Node Count',
      podCount: 'Pod Count',
      podCountLabel: 'Pod Count',
      cpuUsageLabel: 'CPU Usage',
      memoryUsageLabel: 'Memory Usage',
      datacenterLabel: 'Datacenter',
      evictPod: 'Evict Pod',
      setTaint: 'Set Taint',
      deleteNode: 'Delete Node',
      searchNodePlaceholder: 'Search node',
      nodeName: 'Node Name',
      role: 'Role',
      operations: 'Operations',
      podDeleted: 'Pod Deleted',
      podRestarted: 'Pod Restarted',
      status: 'Status',
      cpuUsage: 'CPU Usage',
      memoryUsage: 'Memory Usage',
      // Pod list fields
      podName: 'Pod Name',
      namespace: 'Namespace',
      cluster: 'Cluster',
      node: 'Node',
      containers: 'Containers',
      restartCount: 'Restart Count',
      runningTime: 'Running Time',
      searchPodPlaceholder: 'Search Pod',
      clusterFilter: 'Cluster Filter',
      allClusters: 'All Clusters',
      namespaceFilter: 'Namespace Filter',
      allNamespaces: 'All Namespaces',
      statusFilter: 'Status Filter',
      allStatus: 'All Status',
      totalPods: 'Total Pods',
      podRunning: 'Running Pods',
      podPending: 'Pending Pods',
      podFailed: 'Failed Pods',
      podSucceeded: 'Succeeded Pods',
      podUnknown: 'Unknown Pods',
      podStatusRunning: 'Running',
      podStatusPending: 'Pending',
      podStatusSucceeded: 'Succeeded',
      podStatusFailed: 'Failed',
      podStatusUnknown: 'Unknown',
      containerCount: 'Container Count',
      containerReady: 'Container Ready',
    },
    deploy: {
      title: 'Component Deployment',
      description: 'Deploy Components',
      componentLibrary: 'Component Library',
      deployHistory: 'Deploy History',
      deploy: 'Deploy',
      rollback: 'Rollback',
      startDeploy: 'Start Deploy',
      availableComponents: 'Available Components',
      searchComponents: 'Search Components',
      deploymentTarget: 'Deployment Target',
      progressComplete: 'Progress Complete',
      target: 'Target',
      completed: 'Completed',
      categories: {
        basic: 'Basic',
        database: 'Database',
        container: 'Container',
        monitor: 'Monitor',
        security: 'Security',
      },
      components: {
        nginx: {
          name: 'Nginx',
          description: 'High-performance HTTP and reverse proxy server',
        },
        mysql: {
          name: 'MySQL',
          description: 'Relational database management system',
        },
        redis: {
          name: 'Redis',
          description: 'In-memory data structure store system',
        },
        docker: {
          name: 'Docker',
          description: 'Containerization platform',
        },
        prometheus: {
          name: 'Prometheus',
          description: 'Open-source monitoring system and time series database',
        },
        vault: {
          name: 'Vault',
          description: 'Securely store and manage sensitive data',
        },
      },
      status: {
        success: 'Success',
        running: 'Running',
        failed: 'Failed',
      },
      time: {
        minutesAgo: 'Minutes Ago',
        inProgress: 'In Progress',
        hoursAgo: 'Hours Ago',
      },
    },
    monitor: {
      title: 'Monitoring',
      description: 'System Monitoring',
      alertRules: 'Alert Rules',
      alertHistory: 'Alert History',
      notificationSettings: 'Notification Settings',
      monitorDashboard: 'Monitor Dashboard',
    },
    operations: {
      title: 'Operations Monitoring',
      description: 'System Operations Monitoring',
      realTimeMonitoring: 'Real-time Monitoring',
      systemLogs: 'System Logs',
      opsTasks: 'Operations Tasks',
      alertCenter: 'Alert Center',
      realTimeLogs: 'Real-time Logs',
      opsTaskList: 'Task List',
      alertRecords: 'Alert Records',
      filter: 'Filter',
      export: 'Export',
      createTask: 'Create Task',
      loadMoreLogs: 'Load More Logs',
      alertSettings: 'Alert Settings',
      viewDetails: 'View Details',
      markAsRead: 'Mark as Read',
      progress: 'Progress',
      host: 'Host',
      startTime: 'Start Time',
      metrics: {
        cpuAvgUsage: 'CPU Average Usage',
        memoryAvgUsage: 'Memory Average Usage',
        diskUsage: 'Disk Usage',
        networkTraffic: 'Network Traffic',
      },
      status: {
        running: 'Running',
        completed: 'Completed',
        scheduled: 'Scheduled',
      },
      tasks: {
        batchUpdateHosts: 'Batch Update Hosts',
        databaseBackup: 'Database Backup',
        cleanTempFiles: 'Clean Temp Files',
      },
      alerts: {
        cpuAlert: 'CPU Alert',
        nodeUnavailable: 'Node Unavailable',
        diskSpaceAlert: 'Disk Space Alert',
      },
    },
  },
};

function applyLocaleOverrides(target: Record<string, unknown>, source: Record<string, unknown>) {
  Object.entries(source).forEach(([key, value]) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      const current = target[key];
      const nextTarget =
        current && typeof current === 'object' && !Array.isArray(current)
          ? (current as Record<string, unknown>)
          : {};
      target[key] = nextTarget;
      applyLocaleOverrides(nextTarget, value as Record<string, unknown>);
      return;
    }

    target[key] = value;
  });
}

const zhTranslationOverrides = {
  common: {
    confirm: '确认',
    cancel: '取消',
    all: '全部',
    selectAll: '全选',
    deselectAll: '取消全选',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    view: '查看',
    search: '搜索',
    reset: '重置',
    submit: '提交',
    back: '返回',
    next: '下一步',
    close: '关闭',
    copy: '复制',
    loading: '加载中...',
    noData: '暂无数据',
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '提示',
    actions: '操作',
    remark: '备注',
    createdAt: '创建时间',
    updatedAt: '更新时间',
    time: '时间',
    logTime: '日志时间',
    pleaseLogin: '请先登录',
    permissionDenied: '权限不足，无法访问当前页面',
    roleDenied: '角色权限不足，无法访问当前页面',
    noPermissionTitle: '无访问权限',
    noPermissionHint: '抱歉，您没有访问当前页面的权限，请联系管理员授权。',
    settings: '设置',
  },
  systemManage: {
    importExport: {
      importTitle: '导入数据',
      exportTitle: '导出数据',
      supportFiles: '支持 .xlsx、.csv 文件',
      exportFormat: '导出格式',
      clickToUpload: '点击上传',
      dragAndDrop: '或拖拽文件到此处',
      maxSize: '最大 10MB',
      downloadTemplate: '下载模板',
      processing: '处理中...',
      exportAll: '导出全部数据',
      exportSelected: '导出所选数据',
      error: '文件格式不正确，请上传 Excel 或 CSV 文件',
      importSuccess: '成功导入 {count} 条记录',
    },
  },
  system: {
    title: 'Pantheon',
    subtitle: '企业运维管理平台',
    admin: '管理员',
    adminEmail: 'admin@example.com',
    addMenuTitle: '新增菜单',
    addMenuDescription: '创建新的系统菜单或按钮权限',
    addRoleTitle: '新增角色',
    addRoleDescription: '创建新的系统角色并配置菜单权限',
    addUserTitle: '新增用户',
    addUserDescription: '创建新的系统用户',
  },
  topBar: {
    searchPlaceholder: '搜索...',
    theme: '主题',
    language: '语言',
    languageChinese: '中文',
    languageEnglish: 'English',
    notifications: '通知',
    myAccount: '我的账户',
    profile: '个人资料',
    profileCenter: '个人中心',
    accountSettings: '设置',
    logout: '退出登录',
    noNewNotifications: '暂无新通知',
  },
  notification: {
    title: '通知中心',
    inbox: '收件箱',
    templates: '通知模板',
  },
  footer: {
    copyright: 'Pantheon 平台',
    database: '数据库',
    cache: '缓存',
    systemStatus: '系统运行状态',
    normal: '正常',
    error: '异常',
  },
  menu: {
    dashboard: '仪表盘',
    systemOverview: '系统概览',
    hosts: '主机管理',
    k8s: 'K8s',
    k8sClusters: 'K8s 集群',
    k8sNodes: 'K8s 节点',
    k8sWorkloads: 'K8s 工作负载',
    k8sNetwork: 'K8s 网络',
    k8sRouting: 'K8s 路由',
    deploy: '部署中心',
    operations: '运维中心',
    alert: '监控告警',
    alertMonitor: '监控中心',
    alertManagement: '告警管理',
    alertRules: '告警规则',
    alertHistory: '告警历史',
    alertNotification: '通知设置',
    system: '系统管理',
    systemUsers: '用户管理',
    systemDepartments: '部门管理',
    systemPositions: '岗位管理',
    systemRoles: '角色管理',
    systemMenus: '菜单管理',
    systemPermissions: '权限管理',
    systemLogs: '日志管理',
    systemAudit: '审计日志',
    systemSettings: '系统设置',
    systemDictionary: '数据字典',
    systemMonitor: '系统监控',
    systemLogManagement: '日志管理',
    profile: '个人中心',
    tenantManagement: '租户管理',
  },
  systemManagement: {
    title: '系统管理',
    description: '管理系统用户、权限与全局配置',
    permissionMatrix: '权限矩阵',
    permissionAudit: '权限审计',
    loginLogs: '登录日志',
    dashboard: {
      location: '上海，中国',
      greetings: {
        morning: '早上好',
        afternoon: '下午好',
        evening: '晚上好',
      },
      adminFallback: '管理员',
      welcomeBack: '欢迎回到 Pantheon 管理后台',
      currentDate: '当前日期',
      quickActions: {
        addUser: '新增用户',
        authorizeRole: '角色授权',
        configureMenu: '菜单配置',
        manageDictionary: '字典管理',
        auditLogs: '审计日志',
        databaseBackup: '数据库备份',
      },
    },
    roles: {
      usersDialog: {
        title: '角色成员管理',
        description: '为角色添加或移除成员，维护角色成员列表。',
        tabCurrent: '当前成员',
        tabAdd: '添加成员',
        searchPlaceholder: '搜索姓名、用户名或邮箱...',
        selectedLabel: '已选择',
        emptyCurrent: '当前角色暂无成员',
        emptySearch: '未找到匹配用户',
        removeSelected: '移除所选',
        addSelected: '添加所选',
        removeSuccess: '成员已移除',
        addSuccess: '成员已添加',
      },
    },
    users: {
      actions: {
        assignRoles: '分配角色',
        resetPassword: '重置密码',
      },
      permissionsPanel: {
        title: '用户权限',
        description: '查看该用户聚合后的权限列表（来源于角色与 Casbin 策略）。',
        total: '总数',
        searchPlaceholder: '搜索权限标识...',
        verifyTitle: '权限校验',
        verifyHint: '输入权限标识进行校验，例如 /api/v1/system/users:get',
        verifyPlaceholder: '请输入权限标识',
        verifyButton: '校验',
        verifyHas: '用户拥有该权限',
        verifyNot: '用户不具备该权限',
      },
      roleAssignDialog: {
        title: '分配角色',
        description: '为当前用户分配或移除角色',
        selectRoles: '选择当前用户的角色',
        systemRole: '系统角色',
        customRole: '自定义角色',
        setExpiry: '设置有效期',
        expiryPlaceholder: '选择到期时间',
        updated: '角色已更新',
        updateFailed: '角色更新失败',
        tipAssignPrefix: '将分配',
        tipRoleSuffix: '个角色',
        tipUntil: '有效至',
        rolesLabel: '选择角色',
        searchPlaceholder: '搜索角色...',
      },
      form: {
        usernamePlaceholder: '请输入用户名',
        realNamePlaceholder: '请输入姓名',
        emailPlaceholder: '请输入邮箱',
        phonePlaceholder: '请输入手机号',
        passwordPlaceholder: '请输入密码',
        departmentPlaceholder: '请选择部门',
        rolePlaceholder: '请选择角色',
        remarkPlaceholder: '请输入备注信息',
      },
    },
    positions: {
      level: '职级',
      levelAll: '全部职级',
      levelL1: 'L1 职级',
      levelL2: 'L2 职级',
      levelL3: 'L3 职级',
    },
    dictionary: {
      typeTitle: '字典分类',
      typeSearchPlaceholder: '搜索分类...',
      typeEmptyHint: '暂无匹配分类',
      searchPlaceholder: '搜索字典项...',
      addItem: '新增字典项',
      typeKey: '分类 Key',
      unselected: '未选择',
      refresh: '刷新',
      addCategoryTodo: '新增分类功能开发中',
      selectTypeFirst: '请先选择一个分类',
      importTodo: '导入功能开发中',
      exportTodo: '正在生成导出文件...',
      created: '字典项已创建',
      updated: '字典项已更新',
      deleted: '字典项已删除',
      typeCreated: '分类已创建',
      typeUpdated: '分类已更新',
      typeDeleted: '分类已删除',
      notSelected: '未选择',
      pageLabel: '页',
      totalLabel: '总计',
      currentType: '当前分类',
      dialogs: {
        addItemTitle: '新增字典项',
        editItemTitle: '编辑字典项',
        addTypeTitle: '新增分类',
        editTypeTitle: '编辑分类',
      },
      fields: {
        type: '分类',
        typeName: '分类名称',
        typeCode: '分类编码',
        label: '字典标签',
        value: '字典值',
        sort: '排序',
        status: '状态',
        remark: '备注',
      },
      placeholders: {
        typeName: '例如：用户状态',
        typeCode: '例如：user_status',
        typeDesc: '请输入分类描述',
        label: '例如：启用',
        value: '例如：active',
        remark: '请输入备注说明',
      },
      validation: {
        required: '请填写必填项',
      },
      columns: {
        label: '字典标签',
        value: '字典值',
        style: '样式预览',
        sort: '排序',
        remark: '备注',
      },
      actions: {
        editItem: '编辑字典项',
      },
      emptyHint: '请选择左侧分类或新增字典项',
      importSuccess: '导入成功',
      exportSuccess: '导出成功',
    },
    menuManagement: {
      typeAll: '全部类型',
      typeDirectory: '目录',
      typeMenu: '菜单',
      typeButton: '按钮',
      searchPlaceholder: '搜索菜单名称、路由或权限标识...',
      typePlaceholder: '选择菜单类型',
      statusAll: '全部状态',
      columns: {
        type: '类型',
        routePermission: '路由/权限',
        sort: '排序',
      },
      actions: {
        addChild: '新增子菜单',
      },
    },
    permissionManagement: {
      clickToCopy: '点击可全选复制',
      pageDescription: '管理系统细粒度权限标识、数据权限和菜单绑定关系，为授权与审计提供基础支撑。',
      batchDelete: '批量删除',
      searchPlaceholder: '搜索权限名称、标识或描述...',
      typePlaceholder: '权限类型',
      modulePlaceholder: '业务模块',
      typeAll: '全部类型',
      typeMenu: '菜单权限',
      typeOperation: '操作权限',
      typeData: '数据权限',
      moduleAll: '全部模块',
      importSuccess: '导入成功',
      exporting: '正在导出...',
      loadFailed: '权限加载失败',
      operation: '操作',
      menu: '菜单',
      data: '数据',
      code: '权限标识',
      name: '权限名称',
      type: '类型',
      module: '模块',
      description: '描述',
    },
    monitor: {
      pageTitle: '系统实时监控',
      pageDescription: '查看系统运行状态、服务健康度与关键资源信息。',
      refresh: '刷新',
      exportSnapshot: '导出快照',
      uptime: '运行时长',
      goroutines: '协程数',
      goVersion: 'Go 版本',
      numCPU: 'CPU 核心数',
      memoryAlloc: '已分配内存',
      memorySys: '系统内存',
      heapAlloc: '堆内存',
      coreResourcesTitle: '核心资源监控',
      coreResourcesDesc: '实时监测核心资源使用趋势',
      cpuUsage: 'CPU 使用率',
      memUsage: '内存使用率',
      diskUsage: '磁盘使用率',
      onlineUsers: '在线用户',
      systemUptime: '系统运行时长',
      serviceHealthTitle: '服务健康状态',
      allServicesRunning: '所有服务运行正常',
    },
    settingsPage: {
      description: '配置系统核心参数、安全策略和第三方集成能力。',
      tipsTitle: '快捷提示',
      tipsDesc: '修改内容会在点击“立即同步”后生效。',
      viewDocs: '查看文档',
      syncing: '正在同步设置...',
      syncSuccess: '设置已更新',
      syncFailed: '设置同步失败',
      resetInfo: '已恢复所有未保存的修改',
      pendingSync: '检测到配置变更',
      pendingSyncCount: '项待同步',
      resetChanges: '重置修改',
      syncNow: '立即同步',
    },
    logs: {
      title: '统一日志审计',
      description: '统一查询登录日志、操作日志和高风险审计日志。',
      detailTitle: '日志详情',
      detailDesc: '详细记录本次操作的环境信息、业务细节与审计结果。',
      tabLogin: '登录',
      tabOperation: '操作',
      tabAudit: '审计',
      deviceBrowser: '设备 / 浏览器',
      batchDeleteSuccess: '日志已删除',
      searchPlaceholder: '搜索用户名、IP 或操作内容...',
      statusAll: '全部状态',
      deleteSelected: '删除所选',
      importTodo: '导入功能开发中',
      exporting: '正在生成导出文件...',
      onlyOperationCanClear: '仅支持清理操作日志',
      cleared: '操作日志已清理',
      stats: {
        total: '总条数',
      },
      columns: {
        user: '用户',
        time: '时间',
        ip: 'IP 地址',
        status: '状态',
        operation: '操作内容',
        error: '错误信息',
      },
      actions: {
        detail: '详情',
      },
      sections: {
        userEnv: '用户环境',
        bizAction: '业务动作',
        impactScope: '影响范围',
        detailNote: '详细描述 / 备注',
      },
      impact: {
        users: '影响 {count} 个用户',
        roles: '影响 {count} 个角色',
        authRefresh: '触发权限刷新',
        sessionRevoke: '强制会话失效',
      },
      fields: {
        username: '操作人',
        time: '发生时间',
        ip: 'IP 地址',
        location: '地理位置',
        module: '所属模块',
        operation: '操作内容',
        resource: '资源类型',
        resourceId: '资源 ID',
        resourceName: '资源名称',
        request: '请求信息',
        requestBody: '请求体',
        responseBody: '响应体',
        detail: '审计详情',
        duration: '耗时',
        device: '设备终端',
        browser: '浏览器',
        logoutTime: '退出时间',
      },
    },
  },
  settings: {
    basic: {
      title: '基础设置',
      description: '配置系统基础信息和全局参数',
      systemName: '系统名称',
      systemNameDesc: '显示在页面标题和登录页的系统名称',
      systemVersion: '系统版本',
      systemVersionDesc: '当前系统版本号',
      companyName: '公司名称',
      companyNameDesc: '显示在页脚的公司名称',
      systemUrl: '系统地址',
      systemUrlDesc: '系统访问的主地址',
      timezone: '时区',
      timezoneDesc: '系统默认时区',
      dateFormat: '日期格式',
      dateFormatDesc: '日期显示格式',
    },
    security: {
      title: '安全设置',
      description: '配置系统安全策略和访问控制',
      passwordMinLength: '密码最小长度',
      passwordMinLengthDesc: '用户密码允许的最少字符数',
      passwordComplexity: '密码复杂度',
      passwordComplexityDesc: '要求包含大小写字母、数字和特殊字符',
      passwordExpireDays: '密码过期天数',
      passwordExpireDaysDesc: '密码强制修改前的天数，0 表示不过期',
      sessionTimeout: '会话超时时间（分钟）',
      sessionTimeoutDesc: '空闲后自动退出登录的时间',
      maxLoginAttempts: '最大登录尝试次数',
      maxLoginAttemptsDesc: '达到指定次数后锁定账号',
      lockoutDuration: '锁定时长（分钟）',
      lockoutDurationDesc: '登录失败后的锁定时长',
      enableTwoFactor: '启用双因子认证',
      enableTwoFactorDesc: '开启可配置的二次认证',
      ipWhitelist: 'IP 白名单',
      ipWhitelistDesc: '允许访问的 IP 列表，每行一个',
    },
    email: {
      title: '邮件设置',
      description: '配置系统邮件服务器',
      emailEnabled: '启用邮件服务',
      emailEnabledDesc: '开启系统邮件通知能力',
      smtpHost: 'SMTP 服务器',
      smtpHostDesc: '邮件服务器地址',
      smtpPort: 'SMTP 端口',
      smtpPortDesc: '邮件服务器端口号',
      smtpSsl: '启用 SSL/TLS',
      smtpSslDesc: '使用安全连接',
      smtpUsername: 'SMTP 用户名',
      smtpUsernameDesc: '邮件服务器登录账号',
      smtpPassword: 'SMTP 密码',
      smtpPasswordDesc: '邮件服务器登录密码',
      emailFrom: '发件人地址',
      emailFromDesc: '系统邮件发件地址',
      emailFromName: '发件人名称',
      emailFromNameDesc: '系统邮件显示名称',
    },
    notification: {
      title: '通知设置',
      description: '配置系统通知和告警规则',
      notifyOnLogin: '登录通知',
      notifyOnLoginDesc: '用户登录时发送通知',
      notifyOnUserCreate: '创建用户通知',
      notifyOnUserCreateDesc: '创建新用户时发送通知',
      notifyOnPermissionChange: '权限变更通知',
      notifyOnPermissionChangeDesc: '用户权限变更时发送通知',
      notifyOnHostDown: '主机离线通知',
      notifyOnHostDownDesc: '主机离线时发送告警',
      notifyOnHighRisk: '高风险操作通知',
      notifyOnHighRiskDesc: '高风险操作时立即发送通知',
    },
    storage: {
      title: '存储设置',
      description: '配置数据存储和备份策略',
      logRetentionDays: '日志保留天数',
      logRetentionDaysDesc: '系统日志自动清理前的保留天数',
      backupEnabled: '自动备份',
      backupEnabledDesc: '启用数据库自动备份',
      backupFrequency: '备份频率',
      backupFrequencyDesc: '数据库备份执行频率',
      backupRetentionCount: '备份保留数量',
      backupRetentionCountDesc: '保留的备份文件最大数量',
      uploadMaxSize: '最大上传大小（MB）',
      uploadMaxSizeDesc: '单个文件上传的最大大小',
    },
    actions: {
      save: '保存设置',
      reset: '重置',
      saved: '已保存',
      resetSuccess: '已恢复默认值',
      required: '必填',
      readonly: '只读',
      enabled: '启用',
      disabled: '禁用',
    },
  },
  sysMonitor: {
    cpu: 'CPU 使用率',
    memory: '内存使用率',
    disk: '磁盘使用率',
    network: '网络流量',
    database: '数据库',
    activeUsers: '活跃用户',
    uptime: '运行时长',
    upload: '上传速度',
    download: '下载速度',
    connections: '连接数',
    systemInfo: '系统信息',
    cpuCores: 'CPU 核心使用率',
    core: '核心',
  },
  actions: {
    add: '新增',
    edit: '编辑',
    delete: '删除',
    detail: '详情',
    search: '搜索',
    export: '导出',
    import: '导入',
    refresh: '刷新',
    filter: '筛选',
  },
  status: {
    enabled: '启用',
    disabled: '禁用',
    active: '激活',
    inactive: '停用',
    online: '在线',
    offline: '离线',
    running: '运行中',
    stopped: '已停止',
    warning: '警告',
    healthy: '健康',
    error: '异常',
    success: '成功',
    failed: '失败',
    scheduled: '已计划',
    completed: '已完成',
  },
  user: {
    username: '用户名',
    password: '密码',
    realName: '姓名',
    email: '邮箱',
    phone: '手机号',
    department: '部门',
    position: '岗位',
    role: '角色',
    status: '状态',
    login: '登录',
    logout: '退出',
    profile: '个人资料',
    changePassword: '修改密码',
  },
  login: {
    title: '登录',
    subtitle: '欢迎使用系统',
    tenantCode: '租户代码',
    tenantCodePlaceholder: '请输入租户代码',
    username: '用户名',
    password: '密码',
    rememberPassword: '记住密码',
    forgotPassword: '忘记密码',
    loginButton: '登录',
    loggingIn: '登录中...',
    otherLoginMethods: '其他登录方式',
    testAccount: '测试账号',
    copyright: '版权所有',
    version: '版本',
    usernamePlaceholder: '请输入用户名',
    passwordPlaceholder: '请输入密码',
    usernameRequired: '用户名不能为空',
    passwordRequired: '密码不能为空',
    loginSuccess: '登录成功',
    loginError: '登录异常',
    loginFailed: '登录失败',
    carousel: {
      item1: {
        title: '强大的主机管理',
        subtitle: '集中管理所有服务器资源',
        description: '支持多云环境，轻松监控和管理成千上万台服务器',
      },
      item2: {
        title: 'K8s 集群编排',
        subtitle: '简化容器编排与部署',
        description: '可视化管理 Kubernetes 集群，一键部署应用',
      },
      item3: {
        title: '智能监控与告警',
        subtitle: '实时监控系统状态',
        description: '智能告警策略，第一时间发现并处理问题',
      },
      item4: {
        title: '安全权限管理',
        subtitle: '企业级安全保障',
        description: '细粒度权限控制，完整审计日志追踪',
      },
    },
  },
  validation: {
    required: '此项为必填项',
    invalidEmail: '邮箱格式不正确',
    invalidPhone: '手机号格式不正确',
    minLength: '至少输入 {min} 个字符',
    maxLength: '最多输入 {max} 个字符',
  },
  profile: {
    title: '个人中心',
    description: '管理个人资料、安全配置与使用偏好。',
    personalInfo: '个人信息',
    security: '安全设置',
    notifications: '通知设置',
    preferences: '偏好设置',
    loginHistory: '登录历史',
    accountSettings: '账号设置',
    avatar: '头像',
    basicInfo: '基本信息',
    contactInfo: '联系方式',
    personalSettings: '个人设置',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    emailNotification: '邮件通知',
    systemNotification: '系统通知',
    theme: '主题',
    language: '语言',
    timezone: '时区',
    dateFormat: '日期格式',
    loginTime: '登录时间',
    ipAddress: 'IP 地址',
    device: '设备',
    location: '位置',
    browser: '浏览器',
    os: '操作系统',
    messages: {
      updateProfileSuccess: '个人资料已更新',
    },
    privacy: {
      privacySettingsSaved: '隐私设置已保存',
      visibility: '可见性设置',
      controlVisibility: '控制个人资料对其他用户的可见范围。',
      showProfile: '公开个人资料',
      allowOtherUsers: '允许其他用户查看你的基础资料。',
      showLastLogin: '显示最近登录',
      exposeLoginTime: '允许展示最近登录时间与相关状态。',
      allowSearch: '允许被搜索',
      allowSearchDiscovery: '允许其他用户通过用户名或姓名搜索到你。',
      dataPrivacy: '数据与隐私',
      improvePerformance: '控制数据使用方式，兼顾隐私与体验。',
      shareActivity: '共享活动状态',
      showOnlineStatus: '向其他用户展示在线状态和活跃情况。',
      collectUsage: '允许收集使用统计',
      allowThirdPartySharing: '允许第三方集成共享',
      approvedIntegrations: '仅向已批准的集成能力共享必要信息。',
      saveSettings: '保存隐私设置',
    },
  },
};

const zhRuntimeCleanupOverrides: Partial<Translations> = {
  common: {
    confirm: '确认',
    cancel: '取消',
    all: '全部',
    selectAll: '全选',
    deselectAll: '取消全选',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    view: '查看',
    search: '搜索',
    reset: '重置',
    submit: '提交',
    back: '返回',
    next: '下一步',
    close: '关闭',
    copy: '复制',
    loading: '加载中...',
    noData: '暂无数据',
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '提示',
    actions: '操作',
    remark: '备注',
    createdAt: '创建时间',
    updatedAt: '更新时间',
    time: '时间',
    logTime: '日志时间',
    pleaseLogin: '请先登录',
    permissionDenied: '当前账号暂无访问权限',
    roleDenied: '当前账号角色权限不足',
    noPermissionTitle: '无访问权限',
    noPermissionHint: '当前页面需要额外授权，请联系管理员处理。',
    settings: '设置',
    addDescription: '请填写新增信息后提交。',
    editDescription: '请确认修改内容后保存。',
  },
  systemManage: {
    importExport: {
      importTitle: '导入数据',
      exportTitle: '导出数据',
      supportFiles: '支持 .xlsx、.csv 文件',
      exportFormat: '导出格式',
      clickToUpload: '点击上传',
      dragAndDrop: '或拖拽文件到此处',
      maxSize: '最大 10MB',
      downloadTemplate: '下载模板',
      processing: '处理中...',
      exportAll: '导出全部数据',
      exportSelected: '导出所选数据',
      error: '文件格式不正确，请上传 Excel 或 CSV 文件',
      importSuccess: '成功导入 {count} 条记录',
    },
  },
  system: {
    title: 'Pantheon',
    subtitle: '企业后台管理平台',
    admin: '管理员',
    adminEmail: 'admin@example.com',
    addMenuTitle: '新增菜单',
    addMenuDescription: '创建新的系统菜单或按钮权限',
    addRoleTitle: '新增角色',
    addRoleDescription: '创建新的系统角色并配置菜单权限',
    addUserTitle: '新增用户',
    addUserDescription: '创建新的系统用户',
  },
  topBar: {
    searchPlaceholder: '搜索...',
    theme: '主题',
    language: '语言',
    languageChinese: '中文',
    languageEnglish: 'English',
    notifications: '通知',
    myAccount: '我的账户',
    profile: '个人资料',
    profileCenter: '个人中心',
    accountSettings: '账户设置',
    logout: '退出登录',
    noNewNotifications: '暂无新通知',
  },
  notification: {
    title: '通知中心',
    inbox: '收件箱',
    templates: '通知模板',
  },
  footer: {
    copyright: 'Pantheon 平台',
    database: '数据库',
    cache: '缓存',
    systemStatus: '系统状态',
    normal: '正常',
    error: '异常',
  },
  menu: {
    dashboard: '仪表盘',
    systemOverview: '系统概览',
    deploy: '部署中心',
    operations: '运维中心',
    system: '系统管理',
    systemUsers: '用户管理',
    systemDepartments: '部门管理',
    systemPositions: '岗位管理',
    systemRoles: '角色管理',
    systemMenus: '菜单管理',
    systemPermissions: '权限管理',
    systemLogs: '日志管理',
    systemSettings: '系统设置',
    systemDictionary: '数据字典',
    systemMonitor: '系统监控',
    tenantManagement: '租户管理',
  },
  systemManagement: {
    title: '系统管理',
    description: '管理用户、组织、岗位、角色、菜单、权限、日志与系统配置',
    loginLogs: '登录日志',
    users: {
      actions: {
        assignRoles: '分配角色',
        resetPassword: '重置密码',
      },
      permissionsPanel: {
        title: '用户权限',
        description: '查看当前用户聚合后的权限列表。',
        total: '总数',
        searchPlaceholder: '搜索权限标识...',
        verifyTitle: '权限校验',
        verifyHint: '输入权限标识进行校验，例如 /api/v1/system/users:get',
        verifyPlaceholder: '请输入权限标识',
        verifyButton: '校验',
        verifyHas: '用户拥有该权限',
        verifyNot: '用户不具备该权限',
      },
      roleAssignDialog: {
        title: '分配角色',
        description: '为当前用户分配或移除角色',
        selectRoles: '选择当前用户的角色',
        systemRole: '系统角色',
        customRole: '自定义角色',
        setExpiry: '设置有效期',
        expiryPlaceholder: '选择到期时间',
        updated: '角色已更新',
        updateFailed: '角色更新失败',
        tipAssignPrefix: '将分配',
        tipRoleSuffix: '个角色',
        tipUntil: '有效至',
        rolesLabel: '选择角色',
        searchPlaceholder: '搜索角色...',
      },
      form: {
        usernamePlaceholder: '请输入用户名',
        realNamePlaceholder: '请输入姓名',
        emailPlaceholder: '请输入邮箱',
        phonePlaceholder: '请输入手机号',
        passwordPlaceholder: '请输入密码',
        departmentPlaceholder: '请选择部门',
        rolePlaceholder: '请选择角色',
        remarkPlaceholder: '请输入备注信息',
      },
    },
    positions: {
      level: '职级',
      levelAll: '全部职级',
      levelL1: 'L1 职级',
      levelL2: 'L2 职级',
      levelL3: 'L3 职级',
    },
    roles: {
      searchPlaceholder: '搜索角色名称、编码或描述...',
      type: '角色类型',
      typeAll: '全部类型',
      typeSystem: '系统角色',
      typeCustom: '自定义角色',
      usersDialog: {
        title: '角色成员管理',
        description: '为角色添加或移除成员，维护角色成员列表。',
        tabCurrent: '当前成员',
        tabAdd: '添加成员',
        searchPlaceholder: '搜索姓名、用户名或邮箱...',
        selectedLabel: '已选择',
        emptyCurrent: '当前角色暂无成员',
        emptySearch: '未找到匹配用户',
        removeSelected: '移除所选',
        addSelected: '添加所选',
        removeSuccess: '成员已移除',
        addSuccess: '成员已添加',
      },
    },
    dictionary: {
      typeTitle: '字典分类',
      typeSearchPlaceholder: '搜索分类...',
      typeEmptyHint: '暂无匹配分类',
      currentType: '当前分类',
      emptyHint: '请选择左侧分类或新增字典项',
      dialogs: {
        addItemTitle: '新增字典项',
        editItemTitle: '编辑字典项',
        addTypeTitle: '新增分类',
        editTypeTitle: '编辑分类',
      },
      fields: {
        type: '分类',
        typeName: '分类名称',
        typeCode: '分类编码',
        label: '字典标签',
        value: '字典值',
        sort: '排序',
        status: '状态',
        remark: '备注',
      },
      placeholders: {
        typeName: '例如：用户状态',
        typeCode: '例如：user_status',
        typeDesc: '请输入分类描述',
        label: '例如：启用',
        value: '例如：active',
        remark: '请输入备注说明',
      },
      columns: {
        label: '字典标签',
        value: '字典值',
        style: '样式预览',
        sort: '排序',
        remark: '备注',
      },
      actions: {
        editItem: '编辑字典项',
      },
    },
    menuManagement: {
      typeAll: '全部类型',
      typeDirectory: '目录',
      typeMenu: '菜单',
      typeButton: '按钮',
      searchPlaceholder: '搜索菜单名称、路由或权限标识...',
      typePlaceholder: '选择菜单类型',
      statusAll: '全部状态',
      columns: {
        type: '类型',
        routePermission: '路由/权限',
        sort: '排序',
      },
      actions: {
        addChild: '新增子菜单',
      },
    },
    permissionManagement: {
      clickToCopy: '点击复制',
      pageDescription: '管理系统细粒度权限标识、数据权限和菜单绑定关系，为授权与审计提供基础支撑。',
      batchDelete: '批量删除',
      searchPlaceholder: '搜索权限名称、标识或描述...',
      typePlaceholder: '权限类型',
      modulePlaceholder: '业务模块',
      typeAll: '全部类型',
      typeMenu: '菜单权限',
      typeOperation: '操作权限',
      typeData: '数据权限',
      moduleAll: '全部模块',
      importSuccess: '导入成功',
      exporting: '正在导出...',
      loadFailed: '权限加载失败',
      total: '权限总数',
      operation: '操作',
      menu: '菜单',
      data: '数据',
      code: '权限标识',
      name: '权限名称',
      type: '类型',
      module: '模块',
      description: '描述',
    },
    monitor: {
      pageTitle: '系统实时监控',
      pageDescription: '查看系统运行状态、服务健康度与关键资源信息。',
      refresh: '刷新',
      exportSnapshot: '导出快照',
      uptime: '运行时长',
      goroutines: '协程数',
      goVersion: 'Go 版本',
      numCPU: 'CPU 核心数',
      memoryAlloc: '已分配内存',
      memorySys: '系统内存',
      heapAlloc: '堆内存',
      coreResourcesTitle: '核心资源监控',
      serviceHealthTitle: '服务健康状态',
      allServicesRunning: '所有服务运行正常',
      redisOnlineTitle: 'Redis 与在线用户',
      onlineUsers: '在线用户',
    },
    settingsPage: {
      pendingSync: '检测到配置变更',
      pendingSyncCount: '项待同步',
      resetChanges: '重置修改',
      syncNow: '立即同步',
    },
    logs: {
      title: '统一日志审计',
      description: '统一查询登录日志、操作日志和高风险审计记录。',
      detailTitle: '日志详情',
      detailDesc: '查看本次操作的环境信息、业务细节与审计结果。',
      tabLogin: '登录',
      tabOperation: '操作',
      deviceBrowser: '设备 / 浏览器',
      searchPlaceholder: '搜索用户名、IP 或操作内容...',
      statusAll: '全部状态',
      deleteSelected: '删除所选',
      importNotSupported: '日志暂不支持导入',
      onlyOperationCanClear: '仅支持清理操作日志',
      cleared: '操作日志已清理',
      stats: {
        total: '总条数',
      },
      columns: {
        user: '用户',
        time: '时间',
        ip: 'IP 地址',
        status: '状态',
        operation: '操作内容',
        error: '错误信息',
      },
      actions: {
        detail: '详情',
      },
      sections: {
        userEnv: '用户环境',
        bizAction: '业务动作',
        impactScope: '影响范围',
        detailNote: '详细描述 / 备注',
      },
      impact: {
        users: '影响 {count} 个用户',
        roles: '影响 {count} 个角色',
        authRefresh: '触发权限刷新',
        sessionRevoke: '强制会话失效',
      },
      fields: {
        username: '操作人',
        time: '发生时间',
        ip: 'IP 地址',
        location: '地理位置',
        module: '所属模块',
        operation: '操作内容',
        resource: '资源类型',
        resourceId: '资源 ID',
        resourceName: '资源名称',
        request: '请求信息',
        requestBody: '请求体',
        responseBody: '响应体',
        detail: '审计详情',
        duration: '耗时',
        device: '设备终端',
        browser: '浏览器',
        logoutTime: '退出时间',
      },
    },
  },
  actions: {
    add: '新增',
    addChild: '新增子项',
    edit: '编辑',
    delete: '删除',
    detail: '详情',
    search: '搜索',
    export: '导出',
    import: '导入',
    refresh: '刷新',
    filter: '筛选',
  },
  status: {
    enabled: '启用',
    disabled: '禁用',
    active: '激活',
    inactive: '停用',
    online: '在线',
    offline: '离线',
    running: '运行中',
    stopped: '已停止',
    warning: '警告',
    healthy: '健康',
    error: '异常',
    success: '成功',
    failed: '失败',
    scheduled: '已计划',
    completed: '已完成',
  },
  user: {
    username: '用户名',
    password: '密码',
    realName: '姓名',
    email: '邮箱',
    phone: '手机号',
    department: '部门',
    position: '岗位',
    role: '角色',
    status: '状态',
    login: '登录',
    logout: '退出',
    profile: '个人资料',
    changePassword: '修改密码',
  },
  login: {
    title: '登录',
    subtitle: '欢迎使用系统',
    tenantCode: '租户代码',
    tenantCodePlaceholder: '请输入租户代码',
    tenantCodeRequired: '请输入租户代码',
    username: '用户名',
    usernamePlaceholder: '请输入用户名',
    usernameRequired: '用户名不能为空',
    password: '密码',
    passwordPlaceholder: '请输入密码',
    passwordRequired: '密码不能为空',
    rememberPassword: '记住密码',
    forgotPassword: '忘记密码',
    loginButton: '登录',
    loggingIn: '登录中...',
    otherLoginMethods: '其他登录方式',
    testAccount: '测试账号',
    copyright: '版权所有',
    version: '版本',
    loginSuccess: '登录成功',
    loginError: '登录异常',
    loginFailed: '登录失败',
    carousel: {
      item1: {
        title: '统一的后台底座',
        subtitle: '集中管理租户、账号与权限体系',
        description: '支持多租户、多语言、权限动态加载与系统管理核心模块。',
      },
      item2: {
        title: '细粒度权限控制',
        subtitle: '角色、菜单、权限联动授权',
        description: '支持用户分配角色、角色绑定菜单与权限、登录后动态初始化权限。',
      },
      item3: {
        title: '可配置认证策略',
        subtitle: '支持二次认证与安全策略扩展',
        description: '适配私有化部署、单体模式以及后续 SaaS / PaaS 扩展场景。',
      },
      item4: {
        title: '可扩展业务模块',
        subtitle: '在底座之上动态挂载业务页面',
        description: '后续新增业务模块时，可通过菜单与路由配置实现动态加载。',
      },
    },
  },
  validation: {
    required: '此项为必填项',
    invalidEmail: '邮箱格式不正确',
    invalidPhone: '手机号格式不正确',
    minLength: '至少输入 {min} 个字符',
    maxLength: '最多输入 {max} 个字符',
  },
  profile: {
    title: '个人中心',
    description: '管理个人资料、安全配置与使用偏好。',
    personalInfo: '个人信息',
    security: '安全设置',
    notifications: '通知设置',
    preferences: '偏好设置',
    loginHistory: '登录历史',
    accountSettings: '账户设置',
    avatar: '头像',
    basicInfo: '基本信息',
    contactInfo: '联系方式',
    personalSettings: '个人设置',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    emailNotification: '邮件通知',
    systemNotification: '系统通知',
    theme: '主题',
    language: '语言',
    timezone: '时区',
    dateFormat: '日期格式',
    loginTime: '登录时间',
    ipAddress: 'IP 地址',
    device: '设备',
    location: '位置',
    browser: '浏览器',
    os: '操作系统',
    messages: {
      updateProfileSuccess: '个人资料已更新',
    },
    privacy: {
      privacySettingsSaved: '隐私设置已保存',
      visibility: '可见性设置',
      controlVisibility: '控制个人资料对其他用户的可见范围。',
      showProfile: '公开个人资料',
      allowOtherUsers: '允许其他用户查看你的基础资料。',
      showLastLogin: '展示最近登录',
      exposeLoginTime: '允许展示最近登录时间与相关状态。',
      allowSearch: '允许被搜索',
      allowSearchDiscovery: '允许其他用户通过用户名或姓名搜索到你。',
      dataPrivacy: '数据与隐私',
      improvePerformance: '控制数据使用方式，兼顾隐私与体验。',
      shareActivity: '共享活动状态',
      showOnlineStatus: '向其他用户展示在线状态和活跃情况。',
      collectUsage: '允许收集使用统计',
      allowThirdPartySharing: '允许第三方集成共享',
      approvedIntegrations: '仅向已批准的集成能力共享必要信息。',
      saveSettings: '保存隐私设置',
    },
  },
};

applyLocaleOverrides(zhTranslations as Record<string, unknown>, zhTranslationOverrides as Record<string, unknown>);
applyLocaleOverrides(zhTranslations as Record<string, unknown>, zhRuntimeCleanupOverrides as Record<string, unknown>);

const safeZhTranslations: Translations = zhTranslations;

const translations: Record<Language, Translations> = {
  zh: safeZhTranslations,
  en: enTranslations,
};

export type AppTranslations = Translations;
export const languageResources = translations;

interface LanguageState {
  language: Language;
  t: Translations;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'en',
      t: translations.en,
      
      setLanguage: (lang: Language) => {
        set({ language: lang, t: translations[lang] });
      },
    }),
    {
      name: 'language-storage-v2',
    }
  )
);
